import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Dashboard',
        translateKey: 'nav.home',
        icon: 'navIcon',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    /** Example purpose only, please remove */
    {
        key: 'contacts',
        path: '/contacts',
        title: 'Contacts',
        translateKey: 'nav.contacts',
        icon: 'navIcon',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'leads',
        path: '/leads',
        title: 'Leads',
        translateKey: 'nav.leads',
        icon: 'navIcon',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'claims',
        path: '/claims-pipeline',
        title: 'Claims',
        translateKey: 'nav.collapseMenu.collapseMenu',
        icon: 'navIcon',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'claims.list',
                path: '/claims',
                title: 'Claims List',
                translateKey: 'nav.claims.list',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'claims.pipeline',
                path: '/claims-pipeline',
                title: 'Pipeline',
                translateKey: 'nav.claims.pipeline',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'claims.sales',
                path: '/sales',
                title: 'Sales',
                translateKey: 'nav.claims.sales',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'claims.processing',
                path: '/processing',
                title: 'Processing',
                translateKey: 'nav.claims.processing',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'claims.job',
                path: '/job',
                title: 'Job',
                translateKey: 'nav.claims.job',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'claims.accounting',
                path: '/accounting',
                title: 'Accounting',
                translateKey: 'nav.claims.accounting',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'claims.negotiations',
                path: '/negotiations',
                title: 'Negotiations',
                translateKey: 'nav.claims.negotiations',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'claims.closeout',
                path: '/close-out',
                title: 'Close Out',
                translateKey: 'nav.claims.close-out',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

    {
        key: 'photos',
        path: '/photos',
        title: 'Photos',
        translateKey: 'nav.photos',
        icon: 'navIcon',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'equipment',
        path: '/equipment',
        title: 'Equipment',
        translateKey: 'nav.equipment',
        icon: 'navIcon',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    // {
    //     key: 'reports',
    //     path: '/reports',
    //     title: 'Reports',
    //     translateKey: 'nav.reports',
    //     icon: 'navIcon',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    {
        key: 'calendar',
        path: '/calendar',
        title: 'Calendar',
        translateKey: 'nav.calendar',
        icon: 'navIcon',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'tasks',
        path: '/tasks',
        title: 'Tasks',
        translateKey: 'nav.tasks',
        icon: 'navIcon',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'activityLog',
        path: '/activityLog',
        title: 'Activity Log',
        translateKey: 'nav.activityLog',
        icon: 'navIcon',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
]

export default navigationConfig
