
import user from '@/assets/Images/user.png'
import type { Columns } from './types'

// Dummy data for columns and tickets

export const initialColumns: Columns = [
    {
        id: 'sales',
        title: 'Sales',
        tasks: [
            {
                id: 'claim-c-1001',
                name: 'Claim #C-1001 – Flooded Kitchen Assessment',
                description: 'Homeowner reported major leak under sink, awaiting adjuster.',
                cover: '',
                dueDate: '',
                labels: ['Qualification'],
                members: [{ id: 'photo', name: 'Photo', email: '', img: user }],
                attachments: [
                    { id: 'attachment-1', name: 'Photo 1', src: '/attachments/photo1.jpg', size: '' },
                    { id: 'attachment-2', name: 'Photo 2', src: '/attachments/photo2.jpg', size: '' },
                ],
                comments: [],
            },
            {
                id: 'claim-c-1002',
                name: 'Claim #C-1002 – Roof Damage from Storm',
                description: 'Client accepted service, awaiting insurance claim number.',
                cover: '',
                dueDate: '',
                labels: ['Close'],
                members: [{ id: 'photo', name: 'Photo', email: '', img: user }],
                attachments: [
                    { id: 'attachment-3', name: 'Photo', src: '/attachments/photo3.jpg', size: '' },
                ],
                comments: [],
            },
        ],
    },
    {
        id: 'processing',
        title: 'Processing',
        tasks: [
            {
                id: 'claim-c-1003',
                name: 'Claim #C-1003 – Fire Damage Inspection',
                description: 'Fire department cleared site, initial cleanup scheduled.',
                cover: '',
                dueDate: '',
                labels: ['Intake'],
                members: [{ id: 'photo', name: 'Photo', email: '', img: user }],
                attachments: [
                    { id: 'attachment-4', name: 'Photo 1', src: '/attachments/photo4.jpg', size: '' },
                    { id: 'attachment-5', name: 'Photo 2', src: '/attachments/photo5.jpg', size: '' },
                ],
                comments: [],
            },
            {
                id: 'claim-c-1004',
                name: 'Claim #C-1004 – Hurricane Impact Windows Replacement',
                description: 'Waiting for subcontractor availability for installation.',
                cover: '',
                dueDate: '',
                labels: ['Scheduling'],
                members: [{ id: 'photo', name: 'Photo', email: '', img: user }],
                attachments: [
                    { id: 'attachment-6', name: 'Photo 1', src: '/attachments/photo6.jpg', size: '' },
                    { id: 'attachment-7', name: 'Photo 2', src: '/attachments/photo7.jpg', size: '' },
                    { id: 'attachment-8', name: 'Photo 3', src: '/attachments/photo8.jpg', size: '' },
                ],
                comments: [],
            },
        ],
    },
    {
        id: 'job',
        title: 'Job',
        tasks: [
            {
                id: 'claim-c-1005',
                name: 'Claim #C-1005 – Mold Remediation in Basement',
                description: 'Equipment ordered, team mobilizing in 2 days.',
                cover: '',
                dueDate: '',
                labels: ['Prep'],
                members: [{ id: 'photo', name: 'Photo', email: '', img: user }],
                attachments: [],
                comments: [],
            },
            {
                id: 'claim-c-1006',
                name: 'Claim #C-1006 – Water Extraction & Drying',
                description: 'High-volume fans deployed, moisture levels being monitored.',
                cover: '',
                dueDate: '',
                labels: ['Perform'],
                members: [{ id: 'photo', name: 'Photo', email: '', img: user }],
                attachments: [],
                comments: [],
            },
            {
                id: 'claim-c-1007',
                name: 'Claim #C-1007 – Structural Compliance Check',
                description: 'Engineer review pending before reconstruction approval.',
                cover: '',
                dueDate: '',
                labels: ['Compliance'],
                members: [{ id: 'photo', name: 'Photo', email: '', img: user }],
                attachments: [],
                comments: [],
            },
        ],
    },
    {
        id: 'accounting',
        title: 'Accounting',
        tasks: [
            {
                id: 'claim-c-1008',
                name: 'Claim #C-1008 – Estimating Labor Costs',
                description: 'Work-hour breakdown submitted for review.',
                cover: '',
                dueDate: '',
                labels: ['Calculate Internal Labor'],
                members: [{ id: 'photos', name: 'Photos', email: '', img: user }],
                attachments: [],
                comments: [],
            },
            {
                id: 'claim-c-1009',
                name: 'Claim #C-1009 – Material Cost Approval',
                description: 'Price comparisons completed, waiting on supplier confirmation.',
                cover: '',
                dueDate: '',
                labels: ['Calculate Material'],
                members: [{ id: 'photos', name: 'Photos', email: '', img: user }],
                attachments: [],
                comments: [],
            },
            {
                id: 'claim-c-1010',
                name: 'Claim #C-1010 – Collecting Insurance Deposit',
                description: 'Partial payment received, processing remaining balance.',
                cover: '',
                dueDate: '',
                labels: ['Collect Deposit'],
                members: [{ id: 'photos', name: 'Photos', email: '', img: user }],
                attachments: [],
                comments: [],
            },
            {
                id: 'claim-c-1011',
                name: 'Claim #C-1011 – Adjuster Assigned',
                description: 'Desk adjuster reviewing claim for final assessment.',
                cover: '',
                dueDate: '',
                labels: ['Desk Adjuster Assigned'],
                members: [{ id: 'photos', name: 'Photos', email: '', img: user }],
                attachments: [],
                comments: [],
            },
        ],
    },
    {
        id: 'negotiation',
        title: 'Negotiation',
        tasks: [
            {
                id: 'claim-c-1012',
                name: 'Claim #C-1012 – Insurance Claim Dispute',
                description: 'Adjuster reduced payout, entering negotiation phase.',
                cover: '',
                dueDate: '',
                labels: ['Mediation'],
                members: [{ id: 'photos', name: 'Photos', email: '', img: user }],
                attachments: [],
                comments: [],
            },
            {
                id: 'claim-c-1013',
                name: 'Claim #C-1013 – Payment Confirmation Pending',
                description: 'Insurance confirmed payment, expected transfer in 3 days.',
                cover: '',
                dueDate: '',
                labels: ['Payment Processed'],
                members: [{ id: 'photos', name: 'Photos', email: '', img: user }],
                attachments: [],
                comments: [],
            },
        ],
    },
    {
        id: 'close-out',
        title: 'Close Out',
        tasks: [
            {
                id: 'claim-c-1014',
                name: 'Claim #C-1014 – Commission Report Submission',
                description: 'Final report being generated, expected submission tomorrow.',
                cover: '',
                dueDate: '',
                labels: ['Commission Report'],
                members: [{ id: 'photos', name: 'Photos', email: '', img: user }],
                attachments: [],
                comments: [],
            },
            {
                id: 'claim-c-1015',
                name: 'Claim #C-1015 – Client Review Request',
                description: 'Customer satisfaction follow-up scheduled for Friday.',
                cover: '',
                dueDate: '',
                labels: ['Call Client for Feedback'],
                members: [{ id: 'photos', name: 'Photos', email: '', img: user }],
                attachments: [],
                comments: [],
            },
            {
                id: 'claim-c-1016',
                name: 'Claim #C-1016 – Testimonial Follow-Up',
                description: 'Client interested in leaving a Google review.',
                cover: '',
                dueDate: '',
                labels: ['Call Client for Recommendation'],
                members: [{ id: 'photos', name: 'Photos', email: '', img: user }],
                attachments: [],
                comments: [],
            },
        ],
    },
];

